### ISSUE TITLE
JQuery errors

### ISSUE THREAD

**Issue by asimzeeshan** [seikan/carotu#2]
Regardless of how I install it (release or git repo), it throws this error immediately on login

```
Uncaught TypeError: Cannot read properties of undefined (reading 'Constructor')
    at machine.min.js:1:11276
```

And when I try to add a "provider" since I need it for the "machine", I get a bunch of these erroors

```
Uncaught ReferenceError: url is not defined
    at HTMLDocument.<anonymous> (machine.min.js:1:11065)
    at e (jquery.min.js:2:27028)
    at t (jquery.min.js:2:27330)
```

Looks like a bug

Installed on PHP 8.2x

**Comment by asimzeeshan** [comment]
@seikan Can you help me here please?

**Comment by asimzeeshan** [comment]
@seikan Can you help me here please?

**Comment by asimzeeshan** [comment]
I tried running on a different machine and this time it is working fine, therefore it is no longer an issue for me
